---
- name: Generate encryption keys for file plugin
  shell: echo "1;$(openssl rand -hex 16)" > {{mysql_encryption_key_plugin_options.file_key_management_filename}}
  args:
    creates: '{{mysql_encryption_key_plugin_options.file_key_management_filename}}'

- name: Find if file plugin has been installed
  command: >
    mysql -uroot -p'{{mysql_root_password}}' -sN -e 'SELECT COUNT(*) FROM INFORMATION_SCHEMA.PLUGINS WHERE PLUGIN_NAME = "file_key_management";'
  register: mysql__r_key_plugin_installed
  changed_when: false
  check_mode: no

- block:
    - name: Prepare config to install file plugin
      copy: dest=/etc/my.cnf.d/z_install_key_plugin.cnf content='[mysqld]\nloose-file-key-management-filename'

    - name: Install file plugin
      command: >
        mysql -uroot -p'{{mysql_root_password}}' -e 'install plugin file_key_management soname "file_key_management";'

    - name: Install file plugin
      file: path=/etc/my.cnf.d/z_install_key_plugin.cnf state=absent

  when: mysql__r_key_plugin_installed.stdout | int < 1

- name: Configure encryption
  template: dest=/etc/my.cnf.d/server-encryption.cnf src=server-encryption.cnf.j2 owner=root group=root mode=0644
  notify: Restart mysql
