---
- name: Add repo
  yum_repository: file=mysql-community name={{item}} description='{{item}}' enabled=no baseurl=http://repo.mysql.com/yum/{{item}}/el/{{ansible_distribution_major_version}}/$basearch/ gpgcheck=yes gpgkey=http://repo.mysql.com/RPM-GPG-KEY-mysql state=present owner=root group=root mode=0644
  with_items:
    - mysql-{{mysql_version}}-community
    - mysql-tools-community
    - mysql-connectors-community

- name: Install packages
  yum: name={{item}} state=present enablerepo=mysql-{{mysql_version}}-community
  with_items:
    - mysql-community-server
    - MySQL-python

- name: Install development packages
  yum: name=mysql-devel state=present enablerepo=mysql-{{mysql_version}}-community
  when: mysql_packages_dev

- name: Make sure datadir is present
  file: path={{mysql_datadir}} state=directory owner=mysql group=mysql mode=0755

- name: Configure server
  template: dest=/etc/my.cnf src=my.cnf.j2 owner=root group=root mode=0644
  notify: Restart mysql

- name: Enable service
  service: name=mysqld state=started enabled=yes

- name: Secure installation
  mysql_user: name=root host={{item}} check_implicit_admin=yes password='{{mysql_root_password}}' login_user=root login_password='{{mysql_root_password}}'
  with_items:
    - '{{ansible_fqdn|lower()}}'
    - '{{ansible_hostname|lower()}}'
    - localhost
    - 127.0.0.1
    - ::1
  when: mysql_version | version_compare('5.7', '<') and mysql_root_password != ''

- name: Remove anonymous users
  mysql_user: name='' host={{item}} state=absent login_user=root login_password='{{mysql_root_password}}'
  with_items:
    - '{{ansible_hostname|lower()}}'
    - '{{ansible_fqdn|lower()}}'
    - localhost
  when: mysql_version | version_compare('5.7', '<')

- name: Remove test database
  mysql_db: name=test state=absent login_user=root login_password='{{mysql_root_password}}'
  when: mysql_version | version_compare('5.7', '<')

- name: Add databases
  mysql_db: name={{item.name}} state=present login_user=root login_password='{{mysql_root_password}}'
  with_items: '{{mysql_databases}}'

- name: Add users
  mysql_user: name={{item.0.user}} host={{item.1}} password='{{item.0.password}}' priv='{{item.0.name}}.*:ALL' state=present login_user=root login_password='{{mysql_root_password}}' append_privs=yes
  with_subelements:
    - '{{mysql_databases}}'
    - hosts

- import_tasks: backup.yml
