---
- name: Add repositories
  yum_repository:
    name: '{{item.name}}'
    baseurl: '{{item.baseurl}}'
    description: '{{item.description | default(item.name)}}'
    file: '{{item.file | default(item.name)}}'
    enabled: '{{item.enabled | default("no")}}'
    gpgcheck: '{{item.gpgcheck | default("no")}}'
    gpgkey: '{{item.gpgkey | default(omit)}}'
    owner: '{{item.owner | default("root")}}'
    group: '{{item.group | default("root")}}'
    mode: '{{item.mode | default(0644)}}'
    state: present
  with_items:
    - '{{mysql_repos}}'

- name: Install packages
  yum: name={{item.name}} state=present enablerepo={{item.repo|default(mysql_repos[0].name)}}
  with_items:
    - '{{mysql_packages}}'

- name: Install development packages
  yum: name={{item.name}} state=present enablerepo={{item.repo|default(mysql_repos[0].name)}}
  with_items:
    - '{{mysql_packages_dev}}'

- name: Make sure datadir is present
  file: path={{mysql_datadir}} state=directory owner=mysql group=mysql mode=0755

- name: Configure server
  template: dest=/etc/my.cnf src=my.cnf.j2 owner=root group=root mode=0644
  notify: Restart mysql

- name: Enable service
  service: name=mysqld state=started enabled=yes

- name: Secure installation
  mysql_user: name=root host={{item}} check_implicit_admin=yes password='{{mysql_root_password}}' login_user=root login_password='{{mysql_root_password}}'
  with_items:
    - '{{ansible_fqdn|lower()}}'
    - '{{ansible_hostname|lower()}}'
    - localhost
    - 127.0.0.1
    - ::1
  when: mysql_secure and mysql_root_password != ''

- name: Remove anonymous users
  mysql_user: name='' host={{item}} state=absent login_user=root login_password='{{mysql_root_password}}'
  with_items:
    - '{{ansible_hostname|lower()}}'
    - '{{ansible_fqdn|lower()}}'
    - localhost
  when: mysql_secure

- name: Remove test database
  mysql_db: name=test state=absent login_user=root login_password='{{mysql_root_password}}'
  when: mysql_secure

- name: Add databases
  mysql_db: name={{item.name}} state=present login_user=root login_password='{{mysql_root_password}}'
  with_items: '{{mysql_databases}}'
  loop_control:
    label: '{{item | combine({"password": "***"})}}'

- name: Add users
  mysql_user: name={{item.0.user}} host={{item.1}} password='{{item.0.password}}' priv='{{item.0.name}}.*:ALL' state=present login_user=root login_password='{{mysql_root_password}}' append_privs=yes
  with_subelements:
    - '{{mysql_databases}}'
    - hosts
  loop_control:
    label: '{{[item.0 | combine({"password": "***"}), item.1]}}'

- import_tasks: backup.yml
  when: mysql_backup
